#spring:
#    datasource:
#        driver-class-name: com.mysql.jdbc.Driver
#        url: jdbc:mysql://davy.co.ke/davycoke_world_cup
#        username: davycoke_test
#        password: davycoke_test
#        jdbcUrl: ${spring.datasource.url}
#    jpa:
#        database-platform: org.hibernate.dialect.MySQL5Dialect)
#        hibernate:
#          ddl-auto: update
spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/mydb
#    username: foo
#    password: bar
    driverClassName: org.postgresql.Driver