#spring.boot.admin.client.url: "http://localhost:8000"
##management.endpoints.web.exposure.include: "*"
##spring.boot.admin.url: http://localhost:1111
##spring.boot.admin.username: admin
##spring.boot.admin.password: admin
##
