# spring:
#    datasource:
#        driver-class-name: com.mysql.jdbc.Driver
#        url: jdbc:mysql://localhost:3306/world_cup
#        username: root
#        password: chutha
#        jdbcUrl: ${spring.datasource.url}
#    jpa:
#        database-platform: org.hibernate.dialect.MySQL5Dialect
#        hibernate:
#          ddl-auto: update

# spring.datasource.jdbcUrl=${spring.datasource.url}

#
spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    platform: postgres
    url: jdbc:postgresql://ec2-54-75-227-92.eu-west-1.compute.amazonaws.com:5432/dfe78urtja574b?sslmode=require
    username: mdbduhdwtpxeew
    password: 4ca0fbc46f50323c2f4724d3b914b9eef62029303a649da3e7781b3596faa8d0
    jdbcUrl: ${spring.datasource.url}
    driverClassName: org.postgresql.Driver





#spring:
#    datasource:
#        driver-class-name: com.mysql.jdbc.Driver
#        url: jdbc:mysql://davy.co.ke/davycoke_world_cup
#        username: davycoke_test
#        password: davycoke_test
#        jdbcUrl: ${spring.datasource.url}
#    jpa:
#        database-platform: org.hibernate.dialect.MySQL5Dialect
#        hibernate:
#          ddl-auto: update